name: "Roam Research backup"

on:
  push:
    branches:
      - main
  schedule:
      # Here you can change how often your backup runs. See https://crontab.guru/examples.html
      - cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.BACKUP_REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run Backup
        run: |
          cd /tmp
          git clone -q https://github.com/everruler12/roam2github.git roam2github
          cd $_
          npm i
          npm run backup -s
        env:
          ROAM_EMAIL: ${{ secrets.ROAM_EMAIL }}
          ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          ROAM_GRAPH: ${{ secrets.ROAM_GRAPH }}
          BACKUP_EDN: false
          MD_SKIP_BLANKS: false
          SKIP_BACKLINK_NOTES: true

      - name: Setup dependencies
        run: |
          pip install git+https://github.com/DoomHammer/roam-to-git.git@roam-to-garden
      - name: Generate notes
        run: roam-to-git --skip-fetch --skip-git .
        env:
          ROAMRESEARCH_USER: ${{ secrets.ROAM_EMAIL }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          ROAMRESEARCH_DATABASE: ${{ secrets.ROAM_GRAPH }}
      - name: Commit Changes
        uses: everruler12/git-auto-commit-action@latest
        with:
          commit_message: Automatic backup
